### ISSUE TITLE
Move decision on when to use docker push to docker yaml configs

### ISSUE THREAD

**Issue by hanefi** [citusdata/tools#168]
We have python scripts to update docker files and publish them on DockerHub. These scripts should not decide on when to publish those images, and it should be done via the cli interface, or the yaml config.

For example, we used to have a separate travis job stage for publishing docker images, and we had the conditionals on the same `.travis.yml` file.

https://github.com/citusdata/docker/blob/45da3e65f60f13e23c032ab7577a0c9f4e0a1955/.travis.yml#L5-L6
```yml
  - name: trigger-dockerhub
    if: branch = master AND type != pull_request
```

https://github.com/citusdata/docker/blob/45da3e65f60f13e23c032ab7577a0c9f4e0a1955/.travis.yml#L25-L27
```yml
    - stage: trigger-dockerhub
      name: "Trigger DockerHub Builds"
      script: curl -X POST "$DOCKERHUB_BUILD_TRIGGER"
```

I think the decision on when to push the packages should be the responsibility of the yaml file at the docker repo, and the scope of python scripts should be properly defined and it should behave the same irregardless of the current branch name.

This may require some API changes, and possibly test changes. However it will make debugging things easier IMO.
